---
resource: DOCKER_LINUX_DRIVER
manifest: linux-tools.yml
working_dir: ''
env:
  DOCKER_ENV_VARS: "-e SYSTEM=Ubuntu18.04 -e LINUX_DISTRO=ubuntu -e CCACHE_DIR=/opt/ccache \
    -e MEDIASDK_ROOT=/opt/src/msdk_tools -e LIBVA_REV=va-unified -e MFX_HOME=/opt/src/msdk_repos/mdp_msdk-lib \
    -e MFX_MDF_PATH=/opt/src/msdk_tools/cmrt_linux \
    -e PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig:/usr/local/lib/pkgconfig:/opt/src/msdk_repos/mdp_msdk-contrib/libva/va-unified \
    -e PKG_CONFIG_TOP_BUILD_DIR=/opt/src/msdk_repos/mdp_msdk-contrib/libva/va-unified \
    -e CMAKE_VTUNE_HOME=/opt/src/msdk_repos/mdp_msdk-contrib/itt"
  DOCKER_IMAGE: dockerv2-gfx-build.gfx-assets.intel.com/common/mediasdk-ubuntu18.04:1
qb_variable_map:
  build_version: BUILD_VERSION
  component_name: COMPONENT_NAME
  irepo_workspace: WORKSPACE
  parent_build_id: BUILD_ID
steps:
  - name: mock command in container
    command: echo "Hello world!"
types:
  ubuntu18.04:
    env:
      BUILD_TYPE: Release