---
resource: windows2016v2
working_dir: '..'
manifest: manifest.yml
qb_variable_map:
  build_version: BUILD_VERSION
  component_name: COMPONENT_NAME
  irepo_workspace: WORKSPACE
  parent_build_id: BUILD_ID
  build_number: BUILD_NUMBER
  component_revision: COMPONENT_REVISION
steps:
  - name: copy workspace_snapshot.json
    command: xcopy %WORKSPACE%\..\workspace_snapshot.json %WORKSPACE% /y /q
  - name: copy mediasdk lib repo
    command: (if exist %WORKSPACE%\sources\mdp_msdk-lib rmdir /s /q %WORKSPACE%\sources\mdp_msdk-lib) &&
      (xcopy mediasdk %WORKSPACE%\sources\mdp_msdk-lib\ /s /y /q)
  - name: cleanup output directory
    command: (if exist %WORKSPACE%\output rmdir /s /q %WORKSPACE%\output) && (mkdir %WORKSPACE%\output\packages\windows)
  - name: check python version
    command: python3 --version
  - name: update rc files
    command: python3 %WORKSPACE%\sources\mdp_msdk-lib\config\scripts\update_version.py --path %WORKSPACE%\sources\
      --revision %COMPONENT_REVISION% --build-number %BUILD_NUMBER%
  - name: scroll down (no log here)
    command: .\sources\mdp_msdk-lib\config\scripts\build\windows_build.bat
  - name: build (log replay)
    command: .\sources\mdp_msdk-lib\config\scripts\windows_logs.bat
    always_execute: true
  - name: unit tests x64
    command: ..\..\..\build_tools\cmake\bin\ctest -j %NUMBER_OF_PROCESSORS% --output-on-failure
    working_dir: "../Build/vpl/x64"
  - name: unit tests x32
    command: ..\..\..\build_tools\cmake\bin\ctest -j %NUMBER_OF_PROCESSORS% --output-on-failure
    working_dir: "../Build/vpl/x32"
  - name: create vpl lib drop
    command: powershell -file %WORKSPACE%\sources\mdp_msdk-lib\config\scripts\vpl_windows_drop.ps1
      -BuildDir "%WORKSPACE%\Build" -PathToSave "%WORKSPACE%\output\Windows\vpl\runtime"
  - name: create vpl tools drop
    command: powershell -file %WORKSPACE%\sources\mdp_msdk-lib\config\scripts\vpl_windows_tools_drop.ps1
      -BuildDir "%WORKSPACE%\Build" -Msdk1xPath "%WORKSPACE%\mediasdk_1x_binaries\Windows\msdk\tools\*.zip"
      -PathToSave "%WORKSPACE%\output\Windows\vpl\tools"
types:
  release:
    env:
      BUILD_TYPE: Release
    output:
    - source_dir: "../output/packages/windows"
      file_patterns: "*.zip"
      destination_dir: Packages/windows
    - source_dir: "../output/Windows/vpl/runtime"
      file_patterns: "*.zip"
      destination_dir: Windows/vpl/runtime
    - source_dir: "../output/Windows/vpl/tools"
      file_patterns: "*.zip"
      destination_dir: Windows/vpl/tools
