---
resource: windows2016v2
working_dir: '..'
manifest: manifest.yml
qb_variable_map:
  build_version: BUILD_VERSION
  component_name: COMPONENT_NAME
  irepo_workspace: WORKSPACE
  parent_build_id: BUILD_ID
  build_number: BUILD_NUMBER
  component_revision: COMPONENT_REVISION
env:
  DOCKER_IMAGE: 'dockerv2-gfx-build.gfx-assets.intel.com/common/mediasdk-windows-1803:7'
  DOCKER_WORKSPACE: "C:\\workspace"
  DOCKER_ENV: "-e MEDIASDK_TRS_MODULE_PATH=C:\\workspace\\sources\\msdk_trs_module \
    -e MFX_HOME=C:\\workspace\\sources\\mdp_msdk-lib -e MEDIASDK_ROOT=C:\\workspace\\sources\\msdk_root \
    -e INTELMEDIASDK_FFMPEG_ROOT=C:\\workspace\\sources\\msdk_root\\ffmpeg -e MINIDDK_VERSION=10.0.18362.0"
steps:
  - name: copy workspace_snapshot.json
    command: xcopy %WORKSPACE%\\..\workspace_snapshot.json %WORKSPACE% /y /q
  - name: copy mediasdk lib repo
    command: (if exist %WORKSPACE%\\sources\mdp_msdk-lib rmdir /s /q %WORKSPACE%\\sources\mdp_msdk-lib) &&
      (xcopy mediasdk %WORKSPACE%\\sources\mdp_msdk-lib\ /s /y /q)
  - name: cleanup output directory
    command: (if exist %WORKSPACE%\output rmdir /s /q %WORKSPACE%\output) && (mkdir %WORKSPACE%\output\packages\windows)
  - name: pull docker image
    command: docker pull %DOCKER_IMAGE%
  - name: check python version
    command: python3 --version
  - name: update rc files
    command: python3 %WORKSPACE%\\sources\mdp_msdk-lib\config\scripts\update_version.py --path %WORKSPACE%\\sources\
      --revision %COMPONENT_REVISION% --build-number %BUILD_NUMBER%
  - name: scroll down (no log here)
    command: docker run --rm --storage-opt size=80GB -m 64GB %DOCKER_ENV% -v %WORKSPACE%:%DOCKER_WORKSPACE% %DOCKER_IMAGE%
      call %DOCKER_WORKSPACE%\\sources\mdp_msdk-lib\config\scripts\build\windows_build.bat
  - name: build (log replay)
    command: .\sources\mdp_msdk-lib\config\scripts\windows_logs.bat
    always_execute: true
  - name: create integration lib drop
    command: powershell -file %WORKSPACE%\sources\mdp_msdk-lib\config\scripts\create_windows_drop.ps1
      -BuildDir "%WORKSPACE%\Build" -Msdk1xPath "%WORKSPACE%\mediasdk_1x_binaries\Windows\msdk\runtime\*.zip"
      -PathToSave "%WORKSPACE%\output\Windows\integration\runtime"
  - name: copy integration tools drop
    command: mkdir %WORKSPACE%\output\Windows\integration\tools &&
      xcopy %WORKSPACE%\mediasdk_1x_binaries\Windows\msdk\tools\*.zip %WORKSPACE%\output\Windows\integration\tools
  - name: create vpl lib drop
    command: powershell -file %WORKSPACE%\sources\mdp_msdk-lib\config\scripts\vpl_windows_drop.ps1
      -BuildDir "%WORKSPACE%\Build" -PathToSave "%WORKSPACE%\output\Windows\vpl\runtime"
  - name: create vpl tools drop
    command: powershell -file %WORKSPACE%\sources\mdp_msdk-lib\config\scripts\vpl_windows_tools_drop.ps1
      -BuildDir "%WORKSPACE%\Build" -Msdk1xPath "%WORKSPACE%\mediasdk_1x_binaries\Windows\msdk\tools\*.zip"
      -PathToSave "%WORKSPACE%\output\Windows\vpl\tools"
types:
  release:
    env:
      BUILD_TYPE: Release
    output:
    - source_dir: "../output/packages/windows"
      file_patterns: "*.zip"
      destination_dir: Packages/windows
    - source_dir: "../output/Windows/integration/runtime"
      file_patterns: "*.zip"
      destination_dir: Windows/integration/runtime
    - source_dir: "../output/Windows/integration/tools"
      file_patterns: "*.zip"
      destination_dir: Windows/integration/tools
    - source_dir: "../output/Windows/vpl/runtime"
      file_patterns: "*.zip"
      destination_dir: Windows/vpl/runtime
    - source_dir: "../output/Windows/vpl/tools"
      file_patterns: "*.zip"
      destination_dir: Windows/vpl/tools
