---
resource: windows2016v2
working_dir: '..'
manifest: manifest.yml
qb_variable_map:
  build_version: BUILD_VERSION
  component_name: COMPONENT_NAME
  irepo_workspace: WORKSPACE
  parent_build_id: BUILD_ID
  build_number: BUILD_NUMBER
  component_revision: COMPONENT_REVISION
env:
  DOCKER_IMAGE: 'dockerv2-gfx-build.gfx-assets.intel.com/common/mediasdk-windows-1803:7'
  DOCKER_WORKSPACE: "C:\\workspace"
  DOCKER_ENV: "-e MEDIASDK_TRS_MODULE_PATH=C:\\workspace\\sources\\msdk_trs_module \
    -e MFX_HOME=C:\\workspace\\sources\\mdp_msdk-lib -e MEDIASDK_ROOT=C:\\workspace\\sources\\msdk_root \
    -e INTELMEDIASDK_FFMPEG_ROOT=C:\\workspace\\sources\\msdk_root\\ffmpeg -e MINIDDK_VERSION=10.0.18362.0"
steps:
  - name: copy workspace_snapshot.json
    command: xcopy %WORKSPACE%\\..\workspace_snapshot.json %WORKSPACE% /y /q
  - name: copy mediasdk lib repo
    command: (if exist %WORKSPACE%\\sources\mdp_msdk-lib rmdir /s /q %WORKSPACE%\\sources\mdp_msdk-lib) &&
      (if exist mediasdk (xcopy mediasdk %WORKSPACE%\\sources\mdp_msdk-lib\ /s /y /q)
      else (xcopy product %WORKSPACE%\\sources\mdp_msdk-lib\ /s /y /q))
  - name: pull docker image
    command: docker pull %DOCKER_IMAGE%
  - name: check python version
    command: python3 --version
  - name: update rc files
    command: python3 %WORKSPACE%\\sources\mdp_msdk-lib\config\scripts\update_version.py --path %WORKSPACE%\\sources\
      --revision %COMPONENT_REVISION% --build-number %BUILD_NUMBER%
  - name: build
    command: docker run --rm -t --storage-opt size=80GB -m 64GB %DOCKER_ENV% -v %WORKSPACE%:%DOCKER_WORKSPACE% %DOCKER_IMAGE%
      %DOCKER_WORKSPACE%\\sources\mdp_msdk-lib\config\scripts\windows_build.bat
  - name: create lib drop
    command: docker run --rm -t --storage-opt size=80GB %DOCKER_ENV% -v %WORKSPACE%:%DOCKER_WORKSPACE% %DOCKER_IMAGE%
      powershell -file %DOCKER_WORKSPACE%\sources\mdp_msdk-lib\config\scripts\create_windows_drop.ps1
      -Workspace "C:\workspace" -BuildDir "C:\workspace\Build"
  - name: create tools drop
    command: docker run --rm -t --storage-opt size=80GB %DOCKER_ENV% -v %WORKSPACE%:%DOCKER_WORKSPACE% %DOCKER_IMAGE%
      powershell -file %DOCKER_WORKSPACE%\sources\mdp_msdk-lib\config\scripts\create_windows_tools_drop.ps1
      -Workspace "C:\workspace" -BuildDir "C:\workspace\Build" -ValidationTools "C:\workspace\msdk_binaries\windows_validation_tools"
      -MsdkBinaries "C:\workspace\msdk_binaries\windows_pre_built_binaries" -VPABuildDir "C:\workspace\msdk_binaries\vpa_build"
  - name: create lucas package
    command: docker run --rm -t --storage-opt size=80GB %DOCKER_ENV% -v %WORKSPACE%:%DOCKER_WORKSPACE% %DOCKER_IMAGE%
      powershell -file %DOCKER_WORKSPACE%\sources\mdp_msdk-lib\config\scripts\create_windows_lucas_pkg.ps1
      -Workspace "C:\workspace" -BuildDir "C:\workspace\Build" -ValidationTools "C:\workspace\msdk_binaries\windows_validation_tools"
  - name: create nightly package
    command: docker run --rm -t --storage-opt size=80GB %DOCKER_ENV% -v %WORKSPACE%:%DOCKER_WORKSPACE% %DOCKER_IMAGE%
      powershell -file %DOCKER_WORKSPACE%\sources\mdp_msdk-lib\config\scripts\create_windows_nightly_pkg.ps1
      -Workspace "C:\workspace" -BuildDir "C:\workspace\Build" -VPABuildDir "C:\workspace\msdk_binaries\vpa_build"
      -ValidationTools "C:\workspace\msdk_binaries\windows_validation_tools" -Service_UWD "C:\workspace\msdk_binaries\service" -AMD64 "C:\workspace\msdk_binaries\AMD64"
      -TestSystem "C:\workspace\test_system" -MsdkBinaries "C:\workspace\msdk_binaries\windows_pre_built_binaries"
types:
  release:
    env:
      BUILD_TYPE: Release
    output:
    - source_dir: "../output/packages"
      file_patterns: "*.zip"
      destination_dir: "Windows"
    - source_dir: "../output/WindowsDrop"
      file_patterns: "*.zip"
      destination_dir: "WindowsDrop"
    - source_dir: "../output/WindowsToolsDrop"
      file_patterns: "*.zip"
      destination_dir: "WindowsToolsDrop"
    - source_dir: "../output/LucasPackage"
      file_patterns: "*.zip"
      destination_dir: "WindowsLucasPkg"
    - source_dir: "../output/WindowsNightlyPackage"
      file_patterns: "*.zip"
      destination_dir: "WindowsNightlyPackage"
