version: '1'
components:
  msdk_root:
    type: artifactory
    root_url: https://gfx-assets.intel.com/artifactory
    asset_path: gfx-media-ci-nn/deployment
    asset_name: mediasdk_root
    asset_version: 1
    dest_dir: sources/msdk_root
  msdk_trs_module:
    type: artifactory
    root_url: https://gfx-assets.intel.com/artifactory
    asset_path: gfx-media-ci-nn/deployment
    asset_name: windows_module
    asset_version: 1
    dest_dir: sources/msdk_trs_module
  contrib:
    type: git
    repository: https://github.com/intel-innersource/drivers.gpu.media.sdk.contrib.git
    branch: master
    revision: c93b0ecaca8224683f97d7851775169d53f1e240
    dest_dir: sources/mdp_msdk-contrib
  val-tools:
    type: git
    repository: https://github.com/intel-innersource/drivers.gpu.media.sdk.val-tools.git
    branch: master
    revision: 9bfecbf01987b2ed1088291a0a605e7e8f87bbc2
    dest_dir: sources/mdp_msdk-val-tools
  hevc-stream-generator:
    type: git
    repository: https://github.com/intel-innersource/drivers.gpu.media.sdk.hevc-stream-generator.git
    branch: master
    revision: e067d8203406dd149d9e77a7f9a4ab313d0dedd3
    dest_dir: sources/mdp_msdk-hevc-stream-generator
  mfts:
    type: git
    repository: https://github.com/intel-innersource/drivers.gpu.media.sdk.mfts.git
    branch: master
    revision: 798171e24a19a0f7da58dfd2808e671cb34f7ef1
    dest_dir: sources/mdp_msdk-mfts
  sys-analyzer:
    type: git
    repository: https://github.com/intel-innersource/drivers.gpu.media.sdk.sys-analyzer.git
    branch: master
    revision: 92d49d6fa7b6427ee46d9a6037ae669ff550ccd6
    dest_dir: sources/mdp_msdk-sys-analyzer
  test_system:
    type: git
    repository: https://github.com/intel-innersource/drivers.gpu.media.sdk.tests.git
    branch: master
    revision: c3c4a8f11e180103f874952d2f31286241bc5024
    dest_dir: test_system
  windows_pre_built_binaries:
    type: artifactory
    root_url: https://gfx-assets.fm.intel.com/artifactory
    asset_path: gfx-sandbox-fm/msdk/deployment
    asset_name: msdk_binaries
    asset_version: 201c251804b57f1914579c47ee2c79d07344e1d1_conf_c07719c5_2
    dest_dir: msdk_binaries/windows_pre_built_binaries
  VPA_build:
    type: artifactory
    root_url: https://gfx-assets.fm.intel.com/artifactory
    asset_path: gfx-sandbox-fm/msdk/deployment
    asset_name: VPA_build
    asset_version: 1
    dest_dir: msdk_binaries/vpa_build
  AMD64:
    type: artifactory
    root_url: https://gfx-assets.fm.intel.com/artifactory
    asset_path: gfx-sandbox-fm/msdk/deployment
    asset_name: AMD64
    asset_version: 1
    dest_dir: msdk_binaries/AMD64
  service_UWD:
    type: artifactory
    root_url: https://gfx-assets.fm.intel.com/artifactory
    asset_path: gfx-sandbox-fm/msdk/deployment
    asset_name: service_UWD
    asset_version: 1
    dest_dir: msdk_binaries/service
  windows_validation_tools:
    type: artifactory
    root_url: https://gfx-assets.fm.intel.com/artifactory
    asset_path: gfx-sandbox-fm/msdk/deployment
    asset_name: validation_tools
    asset_version: 1
    dest_dir: msdk_binaries/windows_validation_tools
  nuget_packages:
    type: artifactory
    root_url: https://gfx-assets.fm.intel.com/artifactory
    asset_path: gfx-sandbox-fm/msdk/deployment
    asset_name: nuget_packages
    asset_version: 1
    dest_dir: sources/nuget_packages
  libva:
    type: git
    repository: https://github.com/intel/libva
    branch: master
    revision: 2.9.0.pre1
    dest_dir: libva
  cmrt_linux:
    type: artifactory
    root_url: https://gfx-assets.fm.intel.com/artifactory
    asset_path: gfx-sandbox-fm/msdk/deployment/linux
    asset_name: cmrt_linux
    asset_version: 1
    dest_dir: msdk_root/cmrt_linux
  ipp_linux:
    type: artifactory
    root_url: https://gfx-assets.fm.intel.com/artifactory
    asset_path: gfx-sandbox-fm/msdk/deployment/linux
    asset_name: ipp_linux
    asset_version: 1
    dest_dir: msdk_root/ipp
  test_behavior:
    type: artifactory
    root_url: https://gfx-assets.fm.intel.com/artifactory
    asset_path: gfx-sandbox-fm/msdk/deployment/linux
    asset_name: test_behavior
    asset_version: dab74464a23303359fa4f2db18db0cc86c79d082
    dest_dir: msdk_binaries/test_behavior
  linux_validation_tools:
    type: artifactory
    root_url: https://gfx-assets.fm.intel.com/artifactory
    asset_path: gfx-sandbox-fm/msdk/deployment/linux
    asset_name: validation_tools
    asset_version: 1
    dest_dir: msdk_binaries/linux_validation_tools
  perl:
    type: artifactory
    root_url: https://gfx-assets.fm.intel.com/artifactory
    asset_path: gfx-media-assets/msdk
    asset_name: perl
    asset_version: 5.22.0-win64
    dest_dir: perl
  mediasdk_1x_binaries:
    type: artifactory
    root_url: https://gfx-assets.inn.intel.com/artifactory
    asset_path: mediasdk-builds/ci
    asset_name: mediasdk-1x
    asset_version: mediasdk-ci-mediasdk-1x-1.0.27
    asset_patterns:
    - WindowsDrop/*.zip
    - WindowsToolsDrop/*.zip
    - WindowsLucasPkg/*.zip
    - Linux/Ubuntu/18.04/tools_drop*.zip
    - Linux/Ubuntu/18.04/lucas_linux_drop*.zip
    - Linux/Ubuntu/18.04/l_MSDK_p*.tgz
    dest_dir: mediasdk_1x_binaries
