version: '1'
components:
  msdk_root:
    type: artifactory
    root_url: https://gfx-assets.intel.com/artifactory
    asset_path: gfx-media-ci-nn/deployment
    asset_name: mediasdk_root
    asset_version: 1
    dest_dir: sources/msdk_root
  msdk_trs_module:
    type: artifactory
    root_url: https://gfx-assets.intel.com/artifactory
    asset_path: gfx-media-ci-nn/deployment
    asset_name: windows_module
    asset_version: 1
    dest_dir: sources/msdk_trs_module
  contrib:
    type: git
    repository: https://github.com/intel-innersource/drivers.gpu.media.sdk.contrib.git
    branch: master
    revision: 9b1650011e353061355787b23c53cb8143b7f267
    dest_dir: sources/mdp_msdk-contrib
  val-tools:
    type: git
    repository: https://github.com/intel-innersource/drivers.gpu.media.sdk.val-tools.git
    branch: master
    revision: fec4418ccef65676b827ee1caea620050b7cf0de
    dest_dir: sources/mdp_msdk-val-tools
  test_system:
    type: git
    repository: https://github.com/intel-innersource/drivers.gpu.media.sdk.tests.git
    branch: master
    revision: 2e3690d68c602272287b1d340c1983c997199d66
    dest_dir: test_system
  windows_pre_built_binaries:
    type: artifactory
    root_url: https://gfx-assets.fm.intel.com/artifactory
    asset_path: gfx-sandbox-fm/msdk/deployment
    asset_name: msdk_binaries
    asset_version: 201c251804b57f1914579c47ee2c79d07344e1d1_conf_c07719c5_2
    dest_dir: msdk_binaries/windows_pre_built_binaries
  VPA_build:
    type: artifactory
    root_url: https://gfx-assets.fm.intel.com/artifactory
    asset_path: gfx-sandbox-fm/msdk/deployment
    asset_name: VPA_build
    asset_version: 1
    dest_dir: msdk_binaries/vpa_build
  AMD64:
    type: artifactory
    root_url: https://gfx-assets.fm.intel.com/artifactory
    asset_path: gfx-sandbox-fm/msdk/deployment
    asset_name: AMD64
    asset_version: 1
    dest_dir: msdk_binaries/AMD64
  service_UWD:
    type: artifactory
    root_url: https://gfx-assets.fm.intel.com/artifactory
    asset_path: gfx-sandbox-fm/msdk/deployment
    asset_name: service_UWD
    asset_version: 1
    dest_dir: msdk_binaries/service
  windows_validation_tools:
    type: artifactory
    root_url: https://gfx-assets.fm.intel.com/artifactory
    asset_path: gfx-sandbox-fm/msdk/deployment
    asset_name: validation_tools
    asset_version: 1
    dest_dir: msdk_binaries/windows_validation_tools
  nuget_packages:
    type: artifactory
    root_url: https://gfx-assets.fm.intel.com/artifactory
    asset_path: gfx-sandbox-fm/msdk/deployment
    asset_name: nuget_packages
    asset_version: 1
    dest_dir: sources/nuget_packages
  libva:
    type: git
    repository: https://github.com/intel/libva
    branch: master
    revision: fae0a978c304961b670027f644fb9305c009a9bd
    dest_dir: libva
  cmrt_linux:
    type: artifactory
    root_url: https://gfx-assets.fm.intel.com/artifactory
    asset_path: gfx-sandbox-fm/msdk/deployment/linux
    asset_name: cmrt_linux
    asset_version: 1
    dest_dir: msdk_root/cmrt_linux
  ipp_linux:
    type: artifactory
    root_url: https://gfx-assets.fm.intel.com/artifactory
    asset_path: gfx-sandbox-fm/msdk/deployment/linux
    asset_name: ipp_linux
    asset_version: 1
    dest_dir: msdk_root/ipp
  test_behavior:
    type: artifactory
    root_url: https://gfx-assets.fm.intel.com/artifactory
    asset_path: gfx-sandbox-fm/msdk/deployment/linux
    asset_name: test_behavior
    asset_version: dab74464a23303359fa4f2db18db0cc86c79d082
    dest_dir: msdk_binaries/test_behavior
  linux_validation_tools:
    type: artifactory
    root_url: https://gfx-assets.fm.intel.com/artifactory
    asset_path: gfx-sandbox-fm/msdk/deployment/linux
    asset_name: validation_tools
    asset_version: 1
    dest_dir: msdk_binaries/linux_validation_tools
  perl:
    type: artifactory
    root_url: https://gfx-assets.fm.intel.com/artifactory
    asset_path: gfx-media-assets/msdk
    asset_name: perl
    asset_version: 5.22.0-win64
    dest_dir: perl
  mediasdk_1x_binaries:
    type: artifactory
    root_url: https://gfx-assets.inn.intel.com/artifactory
    asset_path: mediasdk-builds/ci
    asset_name: mediasdk-1x
    asset_version: mediasdk-ci-mediasdk-1x-1.0.82
    asset_patterns:
    - Windows/msdk/runtime/*.zip
    - Windows/msdk/tools/*.zip
    - Ubuntu/msdk/runtime/l_MSDK_p*.tgz
    - Ubuntu/msdk/tools/tools_drop*.zip
    dest_dir: mediasdk_1x_binaries
